/**
 * Differential test: the TypeScript curve maths must agree with the Solidity library exactly.
 *
 * The UI quotes prices locally so it can stay responsive and keep working when an RPC is slow or
 * missing. That is only safe if the local quote is the same number the chain will produce. A
 * one-wei rounding difference does not look like a bug in review — it looks like a transaction
 * that reverts on slippage, or one that fills at a price the user was never shown.
 *
 * The fixtures are generated by `contracts/script/GenerateCurveFixtures.s.sol` running the real
 * on-chain library. If either implementation drifts, this fails.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import {
  CurveError,
  nativeInForExactTokensOut,
  nativeOutForTokensIn,
  spotPriceX18,
  tokensOutForNativeIn,
} from './curve.js';

interface Fixture {
  virtualNative: string;
  virtualToken: string;
  amount: string;
  tokensOutForNativeIn: string;
  nativeOutForTokensIn: string;
  nativeInForExactTokensOut: string | null;
  spotPriceX18: string;
}

const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = resolve(here, '../../../contracts/artifacts/curve-fixtures.json');

const fixtures: Fixture[] = JSON.parse(readFileSync(fixturePath, 'utf8')) as Fixture[];

describe('curve maths matches the on-chain library', () => {
  it('loaded a corpus worth testing against', () => {
    // Guards against the fixture file silently becoming empty and every assertion below
    // vacuously passing.
    expect(fixtures.length).toBeGreaterThan(100);
  });

  it.each(fixtures.map((f, i) => [i, f] as const))(
    'case %i reproduces every on-chain result exactly',
    (_i, f) => {
      const vN = BigInt(f.virtualNative);
      const vT = BigInt(f.virtualToken);
      const amount = BigInt(f.amount);

      expect(tokensOutForNativeIn(vN, vT, amount)).toBe(BigInt(f.tokensOutForNativeIn));
      expect(nativeOutForTokensIn(vN, vT, amount)).toBe(BigInt(f.nativeOutForTokensIn));
      expect(spotPriceX18(vN, vT)).toBe(BigInt(f.spotPriceX18));

      if (f.nativeInForExactTokensOut === null) {
        // Solidity reverts here because the price is unbounded; the port must refuse too, rather
        // than returning a plausible-looking number the chain would never honour.
        expect(() => nativeInForExactTokensOut(vN, vT, amount)).toThrow(CurveError);
      } else {
        expect(nativeInForExactTokensOut(vN, vT, amount)).toBe(
          BigInt(f.nativeInForExactTokensOut),
        );
      }
    },
  );
});

describe('curve maths holds its safety properties independently of the fixtures', () => {
  const V_NATIVE = 1_500_000_000_000_000_000n;
  const V_TOKEN = 1_073_000_000n * 10n ** 18n;

  it('never lets a buy-then-sell round trip profit, across the whole input range', () => {
    // Same property the Solidity fuzz test asserts. Re-checked here because the TypeScript port
    // is what the UI quotes from: if it ever claimed a round trip was profitable, the UI would
    // be inviting users into a trade that loses money every time.
    for (let exp = 0; exp <= 22; exp++) {
      const nativeIn = 10n ** BigInt(exp);
      const bought = tokensOutForNativeIn(V_NATIVE, V_TOKEN, nativeIn);
      if (bought === 0n || bought >= V_TOKEN) continue;

      const returned = nativeOutForTokensIn(V_NATIVE + nativeIn, V_TOKEN - bought, bought);
      expect(returned).toBeLessThanOrEqual(nativeIn);
    }
  });

  it('never lets the constant product decrease on a buy', () => {
    for (let exp = 6; exp <= 21; exp++) {
      const nativeIn = 10n ** BigInt(exp);
      const bought = tokensOutForNativeIn(V_NATIVE, V_TOKEN, nativeIn);
      if (bought === 0n || bought >= V_TOKEN) continue;
      expect((V_NATIVE + nativeIn) * (V_TOKEN - bought)).toBeGreaterThanOrEqual(V_NATIVE * V_TOKEN);
    }
  });

  it('quotes a strictly rising price as the curve is bought into', () => {
    let vN = V_NATIVE;
    let vT = V_TOKEN;
    let previous = spotPriceX18(vN, vT);

    for (let i = 0; i < 40; i++) {
      const bought = tokensOutForNativeIn(vN, vT, 10n ** 17n);
      vN += 10n ** 17n;
      vT -= bought;
      const price = spotPriceX18(vN, vT);
      expect(price).toBeGreaterThanOrEqual(previous);
      previous = price;
    }
  });

  it('refuses to price buying the entire virtual reserve', () => {
    expect(() => nativeInForExactTokensOut(V_NATIVE, V_TOKEN, V_TOKEN)).toThrow(CurveError);
    expect(() => nativeInForExactTokensOut(V_NATIVE, V_TOKEN, V_TOKEN + 1n)).toThrow(CurveError);
  });

  it('rejects non-positive reserves rather than returning nonsense', () => {
    expect(() => tokensOutForNativeIn(0n, V_TOKEN, 1n)).toThrow(CurveError);
    expect(() => nativeOutForTokensIn(V_NATIVE, 0n, 1n)).toThrow(CurveError);
  });
});
